"""EchoProvider — deterministic offline provider.

Used when no API keys are configured, in tests and in the offline demo. It
never claims real work: responses are labeled as offline simulation. It can:

* emit tool calls listed under a `PLANNED_TOOL_CALLS:` block in the prompt so
  the full agent loop (plan → tool → verify → report) runs end-to-end,
* inject failures (n failures then success) to exercise retry logic.

This provider keeps the whole system functional with zero internet access.
"""

from __future__ import annotations

import json
import re

from agentos.config import Settings
from agentos.domain.models import ModelDef, ModelRequest, ModelResponse

from .provider import Provider


def _extract_planned_tool_calls(text: str) -> list[dict]:
    calls: list[dict] = []
    for block in re.findall(r"PLANNED_TOOL_CALLS:\s*(\[.*?\])", text, re.DOTALL):
        try:
            parsed = json.loads(block)
            if isinstance(parsed, list):
                calls.extend(parsed)
        except json.JSONDecodeError:
            continue
    # also accept plain tool_call blocks
    for block in re.findall(r"<tool_call>\s*(\{.*?\})\s*</tool_call>", text, re.DOTALL):
        try:
            parsed = json.loads(block)
            if isinstance(parsed, dict) and "tool" in parsed:
                calls.append(parsed)
        except json.JSONDecodeError:
            continue
    return calls


class EchoProvider(Provider):
    """Deterministic offline provider."""

    name = "echo"

    def __init__(self, settings: Settings, model_defs: dict[str, ModelDef]) -> None:
        super().__init__(settings, model_defs)
        self.fail_remaining: dict[str, int] = {}  # request_id prefix -> failures left

    def inject_failure(self, count: int) -> None:
        """Make the next `count` requests fail (per-process)."""
        self.fail_remaining["__all__"] = self.fail_remaining.get("__all__", 0) + count

    def is_configured(self) -> bool:
        return True

    async def complete(self, request: ModelRequest) -> ModelResponse:
        if self.fail_remaining.get("__all__", 0) > 0:
            self.fail_remaining["__all__"] -= 1
            return ModelResponse(request_id=request.request_id, model_id=request.model_id,
                                 error="simulated provider outage (echo)")
        model = self.model_defs.get(request.model_id) or ModelDef(
            id=request.model_id, provider="echo", name="echo", tier="t2"
        )
        all_text = request.system + "\n" + "\n".join(m.get("content", "") for m in request.messages)
        tool_calls = _extract_planned_tool_calls(all_text)
        # The FIRST user message is the stable task text (later messages are
        # tool results), so auto-generated content stays deterministic.
        task_text = ""
        for m in request.messages:
            if m.get("role") == "user":
                task_text = m.get("content", "")
                break
        # Resolve AUTO contents to a deterministic summary so offline runs
        # still produce real artifacts.
        for call in tool_calls:
            args = call.get("args", {})
            if isinstance(args, dict) and args.get("content") == "AUTO":
                args["content"] = self._auto_content(task_text)
        if not tool_calls:
            # Deterministic fallback: write a summary artifact so the full
            # agent loop (plan → tool → verify → report) runs offline too.
            tool_calls.append({
                "tool": "filesystem.write",
                "args": {"path": "artifacts/echo-summary.md", "content": self._auto_content(task_text)},
            })
        summary = f"[offline-echo] executed task: {task_text[:400] or '(no task text)'}"
        # Build stages (implement-frontend / implement-backend) carry
        # MAX_TOKENS: 16000 and demand raw HTML as the deliverable. Offline,
        # the echo provider ships a complete, self-contained HTML page so the
        # whole pipeline (including the HTML contract) still runs end to end
        # with zero API keys — clearly labeled as an offline simulation.
        if "max_tokens: 16000" in task_text.lower() and "raw html" in task_text.lower():
            content = self._offline_build_html(summary)
        else:
            content = (
                "## Result (offline simulation)\n\n"
                f"{summary}\n\n"
                "> ⚠️ Generated by the EchoProvider for offline testing/demo. No real "
                "research, computation or external action was performed beyond the "
                "tool calls executed by the agent runtime.\n\n"
                "## Reflection\n"
                "- What was asked: see task text above.\n"
                "- What was done: executed the tool calls returned by this simulated model.\n"
                "- What remains: real-model verification once API keys are configured.\n"
            )
        return ModelResponse(
            request_id=request.request_id,
            model_id=request.model_id,
            content=content,
            tool_calls=tool_calls,
            prompt_tokens=len(all_text) // 4,
            completion_tokens=len(content) // 4,
            estimated_cost=0.0,
            finish_reason="stop",
        )

    @staticmethod
    def _offline_build_html(summary: str) -> str:
        """A complete, self-contained HTML page for offline build stages."""
        safe = summary.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        return (
            "<!doctype html>\n"
            "<html lang=\"en\">\n"
            "<head>\n"
            "  <meta charset=\"utf-8\">\n"
            "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
            "  <title>Offline Simulation Build — Agent OS</title>\n"
            "  <style>\n"
            "    :root { color-scheme: light dark; font-family: system-ui, sans-serif; }\n"
            "    main { max-width: 720px; margin: 3rem auto; padding: 0 1rem; }\n"
            "    h1 { font-size: 2rem; } .badge { opacity: .7; font-size: .8rem; }\n"
            "  </style>\n"
            "</head>\n"
            "<body>\n"
            "  <main>\n"
            "    <p class=\"badge\">Offline simulation</p>\n"
            "    <h1>Build complete</h1>\n"
            "    <p>This page was generated by the EchoProvider so the build "
            "stages can run end to end with no API keys.</p>\n"
            "    <pre>" + safe + "</pre>\n"
            "  </main>\n"
            "</body>\n"
            "</html>\n\n"
            "<!-- Generated by the EchoProvider (offline simulation). Replace with "
            "real-model output once API keys are configured. -->"
        )

    @staticmethod
    def _auto_content(last_user: str) -> str:
        excerpt = last_user[:800] if last_user else "(no task text)"
        return (
            "# Offline artifact (EchoProvider)\n\n"
            "Generated during an offline/demo run; content reflects the task "
            "text only. Replace with real-model output once API keys are configured.\n\n"
            "```\n" + excerpt + "\n```\n"
        )